# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-12 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20180421_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.MediaImage'),
        ),
        migrations.AddField(
            model_name='album',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Album ordinal'),
        ),
    ]
