# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import media.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unknown Album', max_length=255, verbose_name='Title of the album')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=media.models.uploaded_filename, verbose_name='Uploaded image')),
                ('thumbnail', models.ImageField(blank=True, upload_to=b'', verbose_name='Thumbnail of uploaded image')),
                ('description', models.TextField(default='', verbose_name='Description of the uploaded image')),
                ('favorite', models.BooleanField(default=False, verbose_name='Image that is a favorite')),
                ('date_created', models.DateField(default=django.utils.timezone.now, verbose_name='Date image was created')),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
        migrations.AddField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(related_name='albums', to='media.MediaImage'),
        ),
    ]
