# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-20 23:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaimage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2018, 4, 20, 23, 44, 7, 499892, tzinfo=utc), verbose_name='Date image was created'),
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='description',
            field=models.TextField(default='', verbose_name='Description of the uploprimary_kepyaded image'),
        ),
    ]
