# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-21 00:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20180420_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaimage',
            name='date_created',
            field=models.DateField(default=datetime.date.today, verbose_name='Date image was created'),
        ),
    ]
