# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-15 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_auto_20180512_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.URLField(blank=True, null=True, verbose_name='Album cover photo'),
        ),
    ]
