# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-17 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMultipleForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending', models.BooleanField(default=True, verbose_name='If person is attending')),
                ('type', models.CharField(max_length=32, verbose_name='Event type')),
                ('number_attending', models.PositiveSmallIntegerField(default=0, verbose_name='number of attendants')),
                ('person', models.ManyToManyField(to='contact.Person', verbose_name='list of attendees')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='bridalshower',
            name='attendants',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='attendants',
        ),
        migrations.DeleteModel(
            name='BridalShower',
        ),
        migrations.DeleteModel(
            name='Wedding',
        ),
    ]
