# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-17 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20190117_0614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventMultipleForm',
            new_name='EventMultiple',
        ),
    ]
