# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-17 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20190117_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending', models.BooleanField(default=True, verbose_name='If person is attending')),
                ('type', models.CharField(max_length=32, verbose_name='Event type')),
                ('number_attending', models.PositiveSmallIntegerField(default=0, verbose_name='number of attendants')),
                ('attendees', models.ManyToManyField(to='contact.Person', verbose_name='list of attendees')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventmultiple',
            name='person',
        ),
        migrations.DeleteModel(
            name='EventMultiple',
        ),
    ]
