# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-17 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20190117_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone number'),
        ),
    ]
