# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-20 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20180420_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaimage',
            name='description',
            field=models.TextField(default='', verbose_name='Description of the uploaded image'),
        ),
    ]
