# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-19 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_auto_20180515_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaimage',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description of the uploaded image'),
        ),
    ]
